### ISSUE TITLE
 run cmd  "composer require jaspervdm/pogoapi-php"  error  

### ISSUE THREAD

**Issue by myshinjio** [jaspervdm/pogoapi-php#5]
```
  [InvalidArgumentException]
  Could not find package jaspervdm/pogoapi-php at any version for your minimum-stability (stable).    Check the package
  spelling or your minimum-stability
```

I run  cmd    error.

> composer require jaspervdm/pogoapi-php

**Comment by jaspervdm** [comment]
You should change your `minimum-stability` to `dev`. This can be done globally (I think), or in your `composer.json`, do:

``` php
{
  "require": {
    "jaspervdm/pogoapi-php": "dev-master"
  },
  "minimum-stability": "dev",
  "prefer-stable": true
}
```

Anyway for now this API lacks a lot of functionality, so I wouldn't recommend using it just yet.
